name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Add musl target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Build
        run: cargo build --release --target=x86_64-unknown-linux-musl
      - name: Rename
        run: cp target/x86_64-unknown-linux-musl/release/zfs-issue-15526-check-file ./zfs-issue-15526-check-file_x86_64-linux
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./zfs-issue-15526-check-file_x86_64-linux
